[build]
    [[redirects]]
    from = "/nominate"
    to = "https://docs.google.com/forms/d/e/1FAIpQLSdYRE0nXymMCJ5WBzPp6xGfhFNqKbOaj7YzZwQqE5oBVSpb6w/viewform?usp=sf_link"
    status = 200
    force = true
